use usiem::events::webproxy::{WebProxyRuleCategory};
// https://www.sonicwall.com/support/knowledge-base/content-filtering-service-cfs-4-0-overview/170505704497427/
pub fn web_category(cat : &str) -> WebProxyRuleCategory {
    match cat {
        "Violence/Hate/Racism" => WebProxyRuleCategory::Violence,
        "Intimate Apparel/SwimSuit" => WebProxyRuleCategory::IntimateApparel,
        "Nudism" => WebProxyRuleCategory::Nudity,
        "Pornography" => WebProxyRuleCategory::Pornography,
        "Weapons" => WebProxyRuleCategory::Weapons,
        "Adult/Mature Content" => WebProxyRuleCategory::MatureContent,
        "Cult/Occult" => WebProxyRuleCategory::Religion,
        "Drugs/Illegal Drugs" => WebProxyRuleCategory::Marijuana,
        "Illegal Skills/Questionable Skills" => WebProxyRuleCategory::QuestionableLegality,
        "Sex Education" => WebProxyRuleCategory::SexEducation,
        "Gambling" => WebProxyRuleCategory::Gambling,
        "Alcohol/Tobacco" => WebProxyRuleCategory::Alcohol,
        "Chat/Instant Messaging (IM)" => WebProxyRuleCategory::OnlineChat,
        "Arts/Entertainment" => WebProxyRuleCategory::ArtCulture,
        "Business and Economy" => WebProxyRuleCategory::BusinessApplications,
        "Abortion/Advocacy Groups" => WebProxyRuleCategory::Abortion,
        "Education" => WebProxyRuleCategory::Education,
        "Cultural Institutions" => WebProxyRuleCategory::ArtCulture,        
        "Online Banking" => WebProxyRuleCategory::Finance,
        "Online Brokerage and Trading" => WebProxyRuleCategory::Trading,
        "Games" => WebProxyRuleCategory::Games,
        "Government" => WebProxyRuleCategory::Government,
        "Military" => WebProxyRuleCategory::Military,
        "Political/Advocacy Groups" => WebProxyRuleCategory::PoliticalAdvocacy,
        "Health" => WebProxyRuleCategory::Health,
        "Information Technology/Computers" => WebProxyRuleCategory::Technology,
        "Hacking/Proxy Avoidance Systems" => WebProxyRuleCategory::ProxyAvoidance,
        "Search Engines and Portals" => WebProxyRuleCategory::SearchEngines,
        "E-Mail" => WebProxyRuleCategory::Email,
        "Web Communications" => WebProxyRuleCategory::Informational,
        "Job Search"  => WebProxyRuleCategory::JobSearch,
        "News and Media" => WebProxyRuleCategory::News,
        "Personals and Dating" => WebProxyRuleCategory::PersonalsDating,
        "Usenet News Groups" => WebProxyRuleCategory::News,
        "Reference" => WebProxyRuleCategory::Reference,
        "Religion" => WebProxyRuleCategory::Religion,
        "Shopping" => WebProxyRuleCategory::Shopping,
        "Internet Auctions" => WebProxyRuleCategory::Auctions,
        "Real Estate" => WebProxyRuleCategory::RealEstate,
        "Society and Lifestyle" => WebProxyRuleCategory::DailyLiving,
        "Restaurants and Dining" => WebProxyRuleCategory::Restaurants,
        "Sports/Recreation" => WebProxyRuleCategory::Sports,
        "Travel" => WebProxyRuleCategory::Travel,
        "Vehicles" => WebProxyRuleCategory::Vehicles,
        "Humor/Jokes" => WebProxyRuleCategory::HumorJokes,
        "Multimedia" => WebProxyRuleCategory::MediaSharing,
        "Freeware/Software Downloads" => WebProxyRuleCategory::PotentiallyUnwantedSoftware,
        "Pay to Surf Sites" => WebProxyRuleCategory::ProxyAvoidance,
        "Kid Friendly" => WebProxyRuleCategory::ForKids,
        "Advertisement" => WebProxyRuleCategory::WebAds,
        "Web Hosting" => WebProxyRuleCategory::WebHosting,
        "Other" => WebProxyRuleCategory::Uncategorized,
        "Internet Watch Foundation CAIC" => WebProxyRuleCategory::InformationSecurity,
        "Social Networking" => WebProxyRuleCategory::SocialNetworking,
        "Malware" => WebProxyRuleCategory::MaliciousSources,
        "Radicalization and Extremism" => WebProxyRuleCategory::QuestionableLegality,
        "Not Rated" => WebProxyRuleCategory::Uncategorized,
        _ => WebProxyRuleCategory::Others(cat.to_string())
    }
}